name = "nccl-test"

[Tests_1]
  name = "nccl_test_all_reduce"
  num_nodes = "2"
  time_limit = "00:20:00"

[Tests_2]
  name = "nccl_test_all_gather"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_2.dependencies]
    start_post_comp = { name = "Tests_1", time = 0 }

[Tests_3]
  name = "nccl_test_reduce_scatter"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_3.dependencies]
    start_post_comp = { name = "Tests_2", time = 0 }

[Tests_4]
  name = "nccl_test_alltoall"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_4.dependencies]
    start_post_comp = { name = "Tests_3", time = 0 }

[Tests_5]
  name = "nccl_test_bisection"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_5.dependencies]
    start_post_comp = { name = "Tests_4", time = 0 }

[Tests_6]
  name = "nccl_test_all_reduce"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_6.dependencies]
    start_post_comp = { name = "Tests_5", time = 0 }

[Tests_7]
  name = "nccl_test_all_gather"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_7.dependencies]
    start_post_comp = { name = "Tests_6", time = 0 }

[Tests_8]
  name = "nccl_test_reduce_scatter"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_8.dependencies]
    start_post_comp = { name = "Tests_7", time = 0 }

[Tests_9]
  name = "nccl_test_alltoall"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_9.dependencies]
    start_post_comp = { name = "Tests_8", time = 0 }

[Tests_10]
  name = "nccl_test_bisection"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_10.dependencies]
    start_post_comp = { name = "Tests_9", time = 0 }

[Tests_11]
  name = "nccl_test_all_reduce"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_11.dependencies]
    start_post_comp = { name = "Tests_10", time = 0 }

[Tests_12]
  name = "nccl_test_all_gather"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_12.dependencies]
    start_post_comp = { name = "Tests_11", time = 0 }

[Tests_13]
  name = "nccl_test_reduce_scatter"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_13.dependencies]
    start_post_comp = { name = "Tests_12", time = 0 }

[Tests_14]
  name = "nccl_test_alltoall"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_14.dependencies]
    start_post_comp = { name = "Tests_13", time = 0 }

[Tests_15]
  name = "nccl_test_bisection"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_15.dependencies]
    start_post_comp = { name = "Tests_14", time = 0 }

[Tests_16]
  name = "nccl_test_all_reduce"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_16.dependencies]
    start_post_comp = { name = "Tests_15", time = 0 }

[Tests_17]
  name = "nccl_test_all_gather"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_17.dependencies]
    start_post_comp = { name = "Tests_16", time = 0 }

[Tests_18]
  name = "nccl_test_reduce_scatter"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_18.dependencies]
    start_post_comp = { name = "Tests_17", time = 0 }

[Tests_19]
  name = "nccl_test_alltoall"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_19.dependencies]
    start_post_comp = { name = "Tests_18", time = 0 }

[Tests_20]
  name = "nccl_test_bisection"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_20.dependencies]
    start_post_comp = { name = "Tests_19", time = 0 }

[Tests_21]
  name = "nccl_test_all_reduce"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_21.dependencies]
    start_post_comp = { name = "Tests_20", time = 0 }

[Tests_22]
  name = "nccl_test_all_gather"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_22.dependencies]
    start_post_comp = { name = "Tests_21", time = 0 }

[Tests_23]
  name = "nccl_test_reduce_scatter"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_23.dependencies]
    start_post_comp = { name = "Tests_22", time = 0 }

[Tests_24]
  name = "nccl_test_alltoall"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_24.dependencies]
    start_post_comp = { name = "Tests_23", time = 0 }

[Tests_25]
  name = "nccl_test_bisection"
  num_nodes = "2"
  time_limit = "00:20:00"
  [Tests_25.dependencies]
    start_post_comp = { name = "Tests_24", time = 0 }
