name = "nccl-test"

[[Tests]]
name = "nccl_test_all_reduce"
num_nodes = 2
time_limit = "00:20:00"

[[Tests]]
name = "nccl_test_all_gather"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.1", time = 0 }

[[Tests]]
name = "nccl_test_reduce_scatter"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.2", time = 0 }

[[Tests]]
name = "nccl_test_alltoall"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.3", time = 0 }

[[Tests]]
name = "nccl_test_bisection"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.4", time = 0 }

[[Tests]]
name = "nccl_test_all_reduce"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.5", time = 0 }

[[Tests]]
name = "nccl_test_all_gather"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.6", time = 0 }

[[Tests]]
name = "nccl_test_reduce_scatter"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.7", time = 0 }

[[Tests]]
name = "nccl_test_alltoall"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.8", time = 0 }

[[Tests]]
name = "nccl_test_bisection"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.9", time = 0 }

[[Tests]]
name = "nccl_test_all_reduce"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.10", time = 0 }

[[Tests]]
name = "nccl_test_all_gather"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.11", time = 0 }

[[Tests]]
name = "nccl_test_reduce_scatter"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.12", time = 0 }

[[Tests]]
name = "nccl_test_alltoall"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.13", time = 0 }

[[Tests]]
name = "nccl_test_bisection"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.14", time = 0 }

[[Tests]]
name = "nccl_test_all_reduce"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.15", time = 0 }

[[Tests]]
name = "nccl_test_all_gather"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.16", time = 0 }

[[Tests]]
name = "nccl_test_reduce_scatter"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.17", time = 0 }

[[Tests]]
name = "nccl_test_alltoall"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.18", time = 0 }

[[Tests]]
name = "nccl_test_bisection"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.19", time = 0 }

[[Tests]]
name = "nccl_test_all_reduce"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.20", time = 0 }

[[Tests]]
name = "nccl_test_all_gather"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.21", time = 0 }

[[Tests]]
name = "nccl_test_reduce_scatter"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.22", time = 0 }

[[Tests]]
name = "nccl_test_alltoall"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.23", time = 0 }

[[Tests]]
name = "nccl_test_bisection"
num_nodes = 2
time_limit = "00:20:00"
[Tests.dependencies]
start_post_comp = { name = "Tests.24", time = 0 }
