name = "nemo_launcher_with_noise"

[Tests_1]
  name = "nemo_launcher"
  num_nodes = "4"
  weight = 100

[Tests_2]
  name = "nccl_test_bisection"
  num_nodes = "16"
  [Tests_2.dependencies]
    start_post_init = { name = "Tests_1", time = 450 }
