name = "nemo_launcher"

[Tests_1]
  name = "nemo_launcher"
  num_nodes = "4"

[Tests_2]
  name = "nemo_launcher"
  num_nodes = "4"
  [Tests_2.dependencies]
    start_post_comp = { name = "Tests_1", time = 0 }

[Tests_3]
  name = "nemo_launcher"
  num_nodes = "4"
  [Tests_3.dependencies]
     start_post_comp = { name = "Tests_2", time = 0 }
