name = "nemo_launcher"

[[Tests]]
name = "nemo_launcher"
num_nodes = 4

[[Tests]]
name = "nemo_launcher"
num_nodes = 4
[Tests.dependencies]
start_post_comp = { name = "Tests.1", time = 0 }

[[Tests]]
name = "nemo_launcher"
num_nodes = 4
[Tests.dependencies]
start_post_comp = { name = "Tests.2", time = 0 }
