name = "nemo_launcher_with_noise"

[[Tests]]
name = "nemo_launcher"
num_nodes = 4
weight = 100

[[Tests]]
name = "nccl_test_bisection"
num_nodes = 16
[Tests.dependencies]
start_post_init = { name = "Tests.1", time = 450 }
