name = "nemo_launcher"

[[Tests]]
test = "nemo_launcher"
name = "Tests.1"
num_nodes = 4

[[Tests]]
test = "nemo_launcher"
name = "Tests.2"
num_nodes = 4
[Tests.dependencies]
start_post_comp = { name = "Tests.1", time = 0 }

[[Tests]]
test = "nemo_launcher"
name = "Tests.3"
num_nodes = 4
[Tests.dependencies]
start_post_comp = { name = "Tests.2", time = 0 }
