name = "nemo_launcher_with_noise"

[[Tests]]
test = "nemo_launcher"
name = "Tests.1"
num_nodes = 4
weight = 100

[[Tests]]
test = "nccl_test_bisection"
name = "Tests.2"
num_nodes = 16
[Tests.dependencies]
start_post_init = { name = "Tests.1", time = 450 }
