name = "test_scenario_example"

[[Tests]]
name = "sleep_10"
[Tests.1.dependencies]
start_post_comp = {}
end_post_comp = {}

[[Tests]]
name = "sleep_5"
[Tests.dependencies]
start_post_init = { name = "Tests.1", time = 5 }
end_post_comp = {}

[[Tests]]
name = "sleep_5"
[Tests.dependencies]
start_post_comp = { name = "Tests.1", time = 0 }
end_post_comp = {}

[[Tests]]
name = "sleep_20"
[Tests.dependencies]
start_post_comp = {}
end_post_comp = { name = "Tests.1", time = 5 }
