name = "ucc_test"

[Tests_1]
  name = "ucc_test_alltoall"
  num_nodes = "2"

[Tests_2]
  name = "ucc_test_alltoall"
  num_nodes = "2"
  [Tests_2.dependencies]
    start_post_comp = { name = "Tests_1", time = 0 }

[Tests_3]
  name = "ucc_test_alltoall"
  num_nodes = "2"
  [Tests_3.dependencies]
    start_post_comp = { name = "Tests_2", time = 0 }

[Tests_4]
  name = "ucc_test_alltoall"
  num_nodes = "2"
  [Tests_4.dependencies]
    start_post_comp = { name = "Tests_3", time = 0 }

[Tests_5]
  name = "ucc_test_alltoall"
  num_nodes = "2"
  [Tests_5.dependencies]
    start_post_comp = { name = "Tests_4", time = 0 }
