# SPDX-FileCopyrightText: NVIDIA CORPORATION & AFFILIATES
# Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name = "vllm"

[[Tests]]
id = "vllm.disagg.4nodes"
test_name = "vllm"
num_nodes = 4
time_limit = "00:30:00"

  [Tests.cmd_args.prefill]
  num_nodes = 2
  enforce_eager = ""
  tensor_parallel_size = 8
  max_num_batched_tokens = 1024

  [Tests.cmd_args.decode]
  num_nodes = 2
  enforce_eager = ""
  tensor_parallel_size = 8
  max_num_batched_tokens = 1024

  [Tests.extra_env_vars]
  CUDA_VISIBLE_DEVICES = "0,1,2,3"

[[Tests]]
id = "vllm.agg.1node"
test_name = "vllm"
num_nodes = 1
time_limit = "00:10:00"

  [Tests.cmd_args.decode]
  enforce_eager = ""
  tensor_parallel_size = 4
  max_num_batched_tokens = 1024

  [Tests.extra_env_vars]
  CUDA_VISIBLE_DEVICES = "0,1,2,3"

[[Tests]]
id = "vllm.agg.2nodes"
test_name = "vllm"
num_nodes = 2
time_limit = "00:30:00"

  [Tests.cmd_args.decode]
  enforce_eager = ""
  tensor_parallel_size = 8
  max_num_batched_tokens = 1024

  [Tests.extra_env_vars]
  CUDA_VISIBLE_DEVICES = "0,1,2,3"

[[Tests]]
id = "vllm.disagg.sync"
test_name = "vllm"
num_nodes = 2
time_limit = "00:30:00"

  [Tests.cmd_args.prefill]
  enforce_eager = ""
  tensor_parallel_size = 4
  max_num_batched_tokens = 1024

  [Tests.cmd_args.decode]
  enforce_eager = ""
  tensor_parallel_size = 4
  max_num_batched_tokens = 1024

  [Tests.extra_env_vars]
  CUDA_VISIBLE_DEVICES = "0,1,2,3"

[[Tests]]
id = "vllm.disagg.async"
test_name = "vllm"
num_nodes = 1
time_limit = "00:10:00"

  [Tests.cmd_args.prefill]
  gpu_ids = "0,1"
  enforce_eager = ""
  tensor_parallel_size = 2
  max_num_batched_tokens = 1024

  [Tests.cmd_args.decode]
  gpu_ids = "2,3"
  enforce_eager = ""
  tensor_parallel_size = 2
  max_num_batched_tokens = 1024

  [Tests.extra_env_vars]
  CUDA_VISIBLE_DEVICES = "0,1,2,3"
