# SPDX-FileCopyrightText: NVIDIA CORPORATION & AFFILIATES
# Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name = "sglang"

[[Tests]]
id = "sglang.agg.2nodes"
test_name = "sglang"
num_nodes = 2
time_limit = "00:10:00"

  [Tests.cmd_args.decode]
  tensor_parallel_size = 2
  mem_fraction_static = 0.75

[[Tests]]
id = "sglang.agg.1node"
test_name = "sglang"
num_nodes = 1
time_limit = "00:10:00"

  [Tests.cmd_args.decode]
  mem_fraction_static = 0.75

[[Tests]]
id = "sglang.disagg.sync"
test_name = "sglang"
num_nodes = 1
time_limit = "00:10:00"

  [Tests.cmd_args.prefill]
  gpu_ids = "0,1"
  tensor_parallel_size = 2
  mem_fraction_static = 0.75

  [Tests.cmd_args.decode]
  gpu_ids = "2,3"
  tensor_parallel_size = 2
  mem_fraction_static = 0.75

[[Tests]]
id = "sglang.disagg.async"
test_name = "sglang"
num_nodes = 1
time_limit = "00:10:00"

  [Tests.cmd_args.prefill]
  gpu_ids = "0,1"
  tensor_parallel_size = 2
  mem_fraction_static = 0.75

  [Tests.cmd_args.decode]
  gpu_ids = "2,3"
  tensor_parallel_size = 2
  mem_fraction_static = 0.75

[[Tests]]
id = "sglang.disagg.2nodes"
test_name = "sglang"
num_nodes = 2
time_limit = "00:10:00"

  [Tests.cmd_args.prefill]
  tensor_parallel_size = 4
  mem_fraction_static = 0.75

  [Tests.cmd_args.decode]
  tensor_parallel_size = 4
  mem_fraction_static = 0.75
