# SPDX-FileCopyrightText: NVIDIA CORPORATION & AFFILIATES
# Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name = "NcclTest"

[cmd_args]
  [cmd_args.docker_image_url]
  type = "str"
  default = "nvcr.io/nvidia/pytorch:24.02-py3"

  [cmd_args.subtest_name]
  type = "preset"
  values = [
    "all_reduce_perf_mpi",
    "all_gather_perf_mpi",
    "alltoall_perf_mpi",
    "broadcast_perf_mpi",
    "gather_perf_mpi",
    "hypercube_perf_mpi",
    "reduce_perf_mpi",
    "reduce_scatter_perf_mpi",
    "scatter_perf_mpi",
    "sendrecv_perf_mpi",
  ]
  default = "all_reduce_perf_mpi"

  [cmd_args.nthreads]
  type = "int"
  default = "1"

  [cmd_args.ngpus]
  type = "int"
  default = "1"

  [cmd_args.minbytes]
  type = "str"
  default = "32M"

  [cmd_args.maxbytes]
  type = "str"
  default = "32M"

  [cmd_args.stepbytes]
  type = "str"
  default = "1M"

  [cmd_args.op]
  type = "preset"
  values = ["sum", "prod", "min", "max", "avg", "all"]
  default = "sum"

  [cmd_args.datatype]
  type = "str"
  default = "float"

  [cmd_args.root]
  type = "int"
  default = "0"

  [cmd_args.iters]
  type = "int"
  default = "20"

  [cmd_args.warmup_iters]
  type = "int"
  default = "5"

  [cmd_args.agg_iters]
  type = "int"
  default = "1"

  [cmd_args.average]
  type = "int"
  default = "1"

  [cmd_args.parallel_init]
  type = "int"
  default = "0"

  [cmd_args.check]
  type = "int"
  default = "1"

  [cmd_args.blocking]
  type = "int"
  default = "0"

  [cmd_args.cudagraph]
  type = "int"
  default = "0"
