# SPDX-FileCopyrightText: NVIDIA CORPORATION & AFFILIATES
# Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name = "UCCTest"

[cmd_args]
  [cmd_args.docker_image_url]
  type = "str"
  default = "nvcr.io/nvidia/pytorch:24.02-py3"

  [cmd_args.collective]
  type = "preset"
  values = [
    "allgather",
    "allgatherv",
    "allreduce",
    "alltoall",
    "alltoallv",
    "barrier",
    "bcast",
    "gather",
    "gatherv",
    "reduce",
    "reduce_scatter",
    "reduce_scatterv",
    "scatter",
    "scatterv",
    "memcpy",
    "reducedt",
    "reducedt_strided",
  ]
  default = "alltoall"

  [cmd_args.b]
  type = "str"
  default = "1"

  [cmd_args.e]
  type = "str"
  default = "8M"
